/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Post {

  /**
   * description of this post
   */
  body: string;

  /**
   * record id
   */
  id: number;

  /**
   * title of this Post
   */
  title: string;

  /**
   * unique user identifier
   */
  userId: string;
}
